excluded:
  - .build/
  - build/
  - MixpanelDemo
  - Sources/SelectorEvaluator.swift
  - Sources/CodelessBinding.swift
  - Sources/TweakViewData.swift
  - Sources/WebSocketWrapper.swift
  - Sources/TakeoverNotificationViewController.swift
  - Sources/ObjectSelector.swift
  - Sources/SnapshotMessage.swift
  - Sources/InAppNotification.swift
  - Sources/DecideRequest.swift
  - Sources/UIControlBinding.swift
  - Sources/InAppNotifications.swift
  - Sources/WebSocket.swift
  - Sources/ObjectFilter.swift
  - Sources/SSLSecurity.swift
  - Sources/NSAttributedStringToNSDictionary.swift
  - Sources/MixpanelNotificationServiceExtension.swift
  - Sources/ObjectSerializer.swift
  - Sources/PushNotifications.swift
  - Sources/ObjectSerializerConfig.swift
  - Sources/TweakPersistency.swift
  - Sources/MD5.swift
  - Sources/BaseWebSocketMessage.swift
  - Sources/BaseNotificationViewController.swift
  - Sources/ObjectIdentityProvider.swift
  - Sources/UITableViewBinding.swift
  - Sources/UIViewSelectors.swift
  - Sources/MiniNotification.swift
  - Sources/VariantAction.swift
  - Sources/DisplayTrigger.swift
  - Sources/MiniNotificationViewController.swift
  - Sources/SHA256.swift
  - Sources/TakeoverNotification.swift
  - Sources/UIColorToNSString.swift
  - Sources/TweakStore.swift
  - Sources/Swizzle.swift
  - Sources/UIImageToNSDictionary.swift
  - Sources/Tweak.swift
  - Sources/DeviceInfoMessage.swift
  - Sources/ApplicationStateSerializer.swift

line_length: 140
file_length: 1500
type_body_length: 500
function_parameter_count: 7
opt_in_rules:
  - empty_count
  - empty_string
  - unused_private_declaration
disabled_rules:
  - cyclomatic_complexity
  - large_tuple
  - conditional_binding_cascade
  - force_cast
  - force_try
  - function_body_length
  - todo
  - type_body_length
  - variable_name
  - trailing_whitespace
