# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

desc "Push a new beta build to TestFlight"
lane :beta do
  build_app(scheme: "LUJO")
  upload_to_testflight
end

desc "Push a new alpha build to Crashlytics"
lane :alpha do
  # increment_build_number

  # build your iOS app
  build_app(
    # scheme: "LUJO",
    export_method: "ad-hoc"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "221292bb9044510d4b6fb6b986ada6984cc76548",
    build_secret: "9b8c9457b4a1aa2ba0e085b4b30a4ce7e74a778d25fba5bfbbe439ebc0451cc8"
  )
end
end
